-- Create industries table
CREATE TABLE IF NOT EXISTS industries (
  id SERIAL PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  category TEXT,
  created_at TIMESTAMP DEFAULT NOW()
);

-- Add industry_id to tenants table
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS industry_id INTEGER REFERENCES industries(id);

-- Create index for faster lookups
CREATE INDEX IF NOT EXISTS idx_tenants_industry_id ON tenants(industry_id);
CREATE INDEX IF NOT EXISTS idx_industries_slug ON industries(slug);
CREATE INDEX IF NOT EXISTS idx_industries_category ON industries(category);

-- Seed industries data
INSERT INTO industries (name, slug, category) VALUES
-- Technology & Software
('Technology & Software', 'technology-software', 'Technology & Software'),
('Software Development', 'software-development', 'Technology & Software'),
('Web Development', 'web-development', 'Technology & Software'),
('Mobile App Development', 'mobile-app-development', 'Technology & Software'),
('SaaS', 'saas', 'Technology & Software'),
('Cloud Computing', 'cloud-computing', 'Technology & Software'),
('Artificial Intelligence', 'artificial-intelligence', 'Technology & Software'),
('Machine Learning', 'machine-learning', 'Technology & Software'),
('Data Analytics', 'data-analytics', 'Technology & Software'),
('Big Data', 'big-data', 'Technology & Software'),
('Cybersecurity', 'cybersecurity', 'Technology & Software'),
('Blockchain', 'blockchain', 'Technology & Software'),
('Web3', 'web3', 'Technology & Software'),
('FinTech', 'fintech', 'Technology & Software'),
('HealthTech', 'healthtech', 'Technology & Software'),
('EdTech', 'edtech', 'Technology & Software'),
('GovTech', 'govtech', 'Technology & Software'),
('InsurTech', 'insurtech', 'Technology & Software'),
('LegalTech', 'legaltech', 'Technology & Software'),
('PropTech', 'proptech', 'Technology & Software'),
('MarTech', 'martech', 'Technology & Software'),

-- Manufacturing & Industrial
('Manufacturing', 'manufacturing', 'Manufacturing & Industrial'),
('Industrial Manufacturing', 'industrial-manufacturing', 'Manufacturing & Industrial'),
('Heavy Industry', 'heavy-industry', 'Manufacturing & Industrial'),
('Light Manufacturing', 'light-manufacturing', 'Manufacturing & Industrial'),
('Automotive Manufacturing', 'automotive-manufacturing', 'Manufacturing & Industrial'),
('Aerospace Manufacturing', 'aerospace-manufacturing', 'Manufacturing & Industrial'),
('Defense Manufacturing', 'defense-manufacturing', 'Manufacturing & Industrial'),
('Electronics Manufacturing', 'electronics-manufacturing', 'Manufacturing & Industrial'),
('Semiconductor Manufacturing', 'semiconductor-manufacturing', 'Manufacturing & Industrial'),
('Machinery Manufacturing', 'machinery-manufacturing', 'Manufacturing & Industrial'),
('Robotics Manufacturing', 'robotics-manufacturing', 'Manufacturing & Industrial'),
('Chemical Manufacturing', 'chemical-manufacturing', 'Manufacturing & Industrial'),
('Pharmaceutical Manufacturing', 'pharmaceutical-manufacturing', 'Manufacturing & Industrial'),
('Medical Device Manufacturing', 'medical-device-manufacturing', 'Manufacturing & Industrial'),
('Textile Manufacturing', 'textile-manufacturing', 'Manufacturing & Industrial'),
('Apparel Manufacturing', 'apparel-manufacturing', 'Manufacturing & Industrial'),
('Food Manufacturing', 'food-manufacturing', 'Manufacturing & Industrial'),
('Beverage Manufacturing', 'beverage-manufacturing', 'Manufacturing & Industrial'),
('Packaging Manufacturing', 'packaging-manufacturing', 'Manufacturing & Industrial'),
('Printing Manufacturing', 'printing-manufacturing', 'Manufacturing & Industrial'),

-- Construction, Engineering & Real Estate
('Construction', 'construction', 'Construction, Engineering & Real Estate'),
('Civil Engineering', 'civil-engineering', 'Construction, Engineering & Real Estate'),
('Structural Engineering', 'structural-engineering', 'Construction, Engineering & Real Estate'),
('Mechanical Engineering', 'mechanical-engineering', 'Construction, Engineering & Real Estate'),
('Electrical Engineering', 'electrical-engineering', 'Construction, Engineering & Real Estate'),
('Architecture', 'architecture', 'Construction, Engineering & Real Estate'),
('Urban Planning', 'urban-planning', 'Construction, Engineering & Real Estate'),
('Infrastructure Development', 'infrastructure-development', 'Construction, Engineering & Real Estate'),
('Real Estate Development', 'real-estate-development', 'Construction, Engineering & Real Estate'),
('Property Management', 'property-management', 'Construction, Engineering & Real Estate'),
('Commercial Real Estate', 'commercial-real-estate', 'Construction, Engineering & Real Estate'),
('Residential Real Estate', 'residential-real-estate', 'Construction, Engineering & Real Estate'),
('Facility Management', 'facility-management', 'Construction, Engineering & Real Estate'),
('Building Materials', 'building-materials', 'Construction, Engineering & Real Estate'),
('Smart Buildings', 'smart-buildings', 'Construction, Engineering & Real Estate'),

-- Healthcare & Life Sciences
('Healthcare Services', 'healthcare-services', 'Healthcare & Life Sciences'),
('Hospitals & Clinics', 'hospitals-clinics', 'Healthcare & Life Sciences'),
('Medical Practices', 'medical-practices', 'Healthcare & Life Sciences'),
('Dental Services', 'dental-services', 'Healthcare & Life Sciences'),
('Veterinary Services', 'veterinary-services', 'Healthcare & Life Sciences'),
('Mental Health Services', 'mental-health-services', 'Healthcare & Life Sciences'),
('Home Healthcare', 'home-healthcare', 'Healthcare & Life Sciences'),
('Elder Care', 'elder-care', 'Healthcare & Life Sciences'),
('Medical Research', 'medical-research', 'Healthcare & Life Sciences'),
('Clinical Research', 'clinical-research', 'Healthcare & Life Sciences'),
('Biotechnology', 'biotechnology', 'Healthcare & Life Sciences'),
('Pharmaceutical Research', 'pharmaceutical-research', 'Healthcare & Life Sciences'),
('Life Sciences', 'life-sciences', 'Healthcare & Life Sciences'),
('Public Health', 'public-health', 'Healthcare & Life Sciences'),
('Health Insurance', 'health-insurance', 'Healthcare & Life Sciences'),

-- Finance, Banking & Insurance
('Banking', 'banking', 'Finance, Banking & Insurance'),
('Retail Banking', 'retail-banking', 'Finance, Banking & Insurance'),
('Investment Banking', 'investment-banking', 'Finance, Banking & Insurance'),
('Corporate Banking', 'corporate-banking', 'Finance, Banking & Insurance'),
('Asset Management', 'asset-management', 'Finance, Banking & Insurance'),
('Wealth Management', 'wealth-management', 'Finance, Banking & Insurance'),
('Insurance', 'insurance', 'Finance, Banking & Insurance'),
('Reinsurance', 'reinsurance', 'Finance, Banking & Insurance'),
('Accounting', 'accounting', 'Finance, Banking & Insurance'),
('Auditing', 'auditing', 'Finance, Banking & Insurance'),
('Tax Advisory', 'tax-advisory', 'Finance, Banking & Insurance'),
('Financial Consulting', 'financial-consulting', 'Finance, Banking & Insurance'),
('Risk Management', 'risk-management', 'Finance, Banking & Insurance'),
('Payments', 'payments', 'Finance, Banking & Insurance'),
('Digital Banking', 'digital-banking', 'Finance, Banking & Insurance'),

-- Retail, Wholesale & E-Commerce
('Retail', 'retail', 'Retail, Wholesale & E-Commerce'),
('Wholesale', 'wholesale', 'Retail, Wholesale & E-Commerce'),
('E-Commerce', 'e-commerce', 'Retail, Wholesale & E-Commerce'),
('Online Marketplaces', 'online-marketplaces', 'Retail, Wholesale & E-Commerce'),
('Fashion Retail', 'fashion-retail', 'Retail, Wholesale & E-Commerce'),
('Luxury Goods', 'luxury-goods', 'Retail, Wholesale & E-Commerce'),
('Consumer Electronics', 'consumer-electronics', 'Retail, Wholesale & E-Commerce'),
('Grocery & Supermarkets', 'grocery-supermarkets', 'Retail, Wholesale & E-Commerce'),
('Convenience Stores', 'convenience-stores', 'Retail, Wholesale & E-Commerce'),
('Specialty Retail', 'specialty-retail', 'Retail, Wholesale & E-Commerce'),
('Direct-to-Consumer (DTC)', 'direct-to-consumer-dtc', 'Retail, Wholesale & E-Commerce'),
('Subscription Commerce', 'subscription-commerce', 'Retail, Wholesale & E-Commerce'),
('Omnichannel Retail', 'omnichannel-retail', 'Retail, Wholesale & E-Commerce'),
('Import & Export', 'import-export', 'Retail, Wholesale & E-Commerce'),
('Merchandising', 'merchandising', 'Retail, Wholesale & E-Commerce'),

-- Logistics, Transportation & Supply Chain
('Logistics', 'logistics', 'Logistics, Transportation & Supply Chain'),
('Supply Chain Management', 'supply-chain-management', 'Logistics, Transportation & Supply Chain'),
('Freight & Shipping', 'freight-shipping', 'Logistics, Transportation & Supply Chain'),
('Maritime Transport', 'maritime-transport', 'Logistics, Transportation & Supply Chain'),
('Aviation & Airlines', 'aviation-airlines', 'Logistics, Transportation & Supply Chain'),
('Rail Transport', 'rail-transport', 'Logistics, Transportation & Supply Chain'),
('Road Transport', 'road-transport', 'Logistics, Transportation & Supply Chain'),
('Courier & Delivery', 'courier-delivery', 'Logistics, Transportation & Supply Chain'),
('Warehousing', 'warehousing', 'Logistics, Transportation & Supply Chain'),
('Distribution', 'distribution', 'Logistics, Transportation & Supply Chain'),
('Fleet Management', 'fleet-management', 'Logistics, Transportation & Supply Chain'),
('Cold Chain Logistics', 'cold-chain-logistics', 'Logistics, Transportation & Supply Chain'),
('International Trade', 'international-trade', 'Logistics, Transportation & Supply Chain'),
('Customs Brokerage', 'customs-brokerage', 'Logistics, Transportation & Supply Chain'),
('Last-Mile Delivery', 'last-mile-delivery', 'Logistics, Transportation & Supply Chain'),

-- Marketing, Media & Communications
('Marketing Services', 'marketing-services', 'Marketing, Media & Communications'),
('Digital Marketing', 'digital-marketing', 'Marketing, Media & Communications'),
('Advertising', 'advertising', 'Marketing, Media & Communications'),
('Media Production', 'media-production', 'Marketing, Media & Communications'),
('Broadcasting', 'broadcasting', 'Marketing, Media & Communications'),
('Publishing', 'publishing', 'Marketing, Media & Communications'),
('Public Relations', 'public-relations', 'Marketing, Media & Communications'),
('Branding Agencies', 'branding-agencies', 'Marketing, Media & Communications'),
('Influencer Marketing', 'influencer-marketing', 'Marketing, Media & Communications'),
('Content Creation', 'content-creation', 'Marketing, Media & Communications'),
('Social Media', 'social-media', 'Marketing, Media & Communications'),
('Performance Marketing', 'performance-marketing', 'Marketing, Media & Communications'),
('Market Research', 'market-research', 'Marketing, Media & Communications'),
('Creative Agencies', 'creative-agencies', 'Marketing, Media & Communications'),
('Communications', 'communications', 'Marketing, Media & Communications'),

-- Education & Training
('Education', 'education', 'Education & Training'),
('Higher Education', 'higher-education', 'Education & Training'),
('Primary Education', 'primary-education', 'Education & Training'),
('Secondary Education', 'secondary-education', 'Education & Training'),
('Vocational Training', 'vocational-training', 'Education & Training'),
('Corporate Training', 'corporate-training', 'Education & Training'),
('Online Education', 'online-education', 'Education & Training'),
('E-Learning Platforms', 'e-learning-platforms', 'Education & Training'),
('Educational Consulting', 'educational-consulting', 'Education & Training'),
('Research Institutions', 'research-institutions', 'Education & Training'),

-- Legal, Government & Public Sector
('Legal Services', 'legal-services', 'Legal, Government & Public Sector'),
('Law Firms', 'law-firms', 'Legal, Government & Public Sector'),
('Corporate Legal Services', 'corporate-legal-services', 'Legal, Government & Public Sector'),
('Government', 'government', 'Legal, Government & Public Sector'),
('Public Administration', 'public-administration', 'Legal, Government & Public Sector'),
('Local Government', 'local-government', 'Legal, Government & Public Sector'),
('National Government', 'national-government', 'Legal, Government & Public Sector'),
('International Organizations', 'international-organizations', 'Legal, Government & Public Sector'),
('NGOs & Nonprofits', 'ngos-nonprofits', 'Legal, Government & Public Sector'),
('Think Tanks', 'think-tanks', 'Legal, Government & Public Sector'),

-- Hospitality, Tourism & Leisure
('Hospitality', 'hospitality', 'Hospitality, Tourism & Leisure'),
('Hotels & Resorts', 'hotels-resorts', 'Hospitality, Tourism & Leisure'),
('Restaurants', 'restaurants', 'Hospitality, Tourism & Leisure'),
('Cafés & Bars', 'cafes-bars', 'Hospitality, Tourism & Leisure'),
('Catering Services', 'catering-services', 'Hospitality, Tourism & Leisure'),
('Travel Agencies', 'travel-agencies', 'Hospitality, Tourism & Leisure'),
('Tourism', 'tourism', 'Hospitality, Tourism & Leisure'),
('Airlines Services', 'airlines-services', 'Hospitality, Tourism & Leisure'),
('Event Management', 'event-management', 'Hospitality, Tourism & Leisure'),
('Recreation & Leisure', 'recreation-leisure', 'Hospitality, Tourism & Leisure'),

-- Agriculture, Food & Natural Resources
('Agriculture', 'agriculture', 'Agriculture, Food & Natural Resources'),
('Farming', 'farming', 'Agriculture, Food & Natural Resources'),
('Livestock', 'livestock', 'Agriculture, Food & Natural Resources'),
('Fisheries', 'fisheries', 'Agriculture, Food & Natural Resources'),
('Aquaculture', 'aquaculture', 'Agriculture, Food & Natural Resources'),
('Forestry', 'forestry', 'Agriculture, Food & Natural Resources'),
('Food Processing', 'food-processing', 'Agriculture, Food & Natural Resources'),
('Agribusiness', 'agribusiness', 'Agriculture, Food & Natural Resources'),
('Organic Farming', 'organic-farming', 'Agriculture, Food & Natural Resources'),
('Sustainable Agriculture', 'sustainable-agriculture', 'Agriculture, Food & Natural Resources'),

-- Energy, Utilities & Environment
('Energy', 'energy', 'Energy, Utilities & Environment'),
('Renewable Energy', 'renewable-energy', 'Energy, Utilities & Environment'),
('Solar Energy', 'solar-energy', 'Energy, Utilities & Environment'),
('Wind Energy', 'wind-energy', 'Energy, Utilities & Environment'),
('Hydropower', 'hydropower', 'Energy, Utilities & Environment'),
('Oil & Gas', 'oil-gas', 'Energy, Utilities & Environment'),
('Utilities', 'utilities', 'Energy, Utilities & Environment'),
('Water Management', 'water-management', 'Energy, Utilities & Environment'),
('Waste Management', 'waste-management', 'Energy, Utilities & Environment'),
('Environmental Services', 'environmental-services', 'Energy, Utilities & Environment'),

-- Gaming, Entertainment & Sports
('Gaming', 'gaming', 'Gaming, Entertainment & Sports'),
('Video Game Development', 'video-game-development', 'Gaming, Entertainment & Sports'),
('Esports', 'esports', 'Gaming, Entertainment & Sports'),
('Entertainment', 'entertainment', 'Gaming, Entertainment & Sports'),
('Film Production', 'film-production', 'Gaming, Entertainment & Sports'),
('Television Production', 'television-production', 'Gaming, Entertainment & Sports'),
('Music Industry', 'music-industry', 'Gaming, Entertainment & Sports'),
('Sports Organizations', 'sports-organizations', 'Gaming, Entertainment & Sports'),
('Fitness & Wellness', 'fitness-wellness', 'Gaming, Entertainment & Sports'),
('Recreation', 'recreation', 'Gaming, Entertainment & Sports'),

-- Professional & Business Services
('Consulting', 'consulting', 'Professional & Business Services'),
('Management Consulting', 'management-consulting', 'Professional & Business Services'),
('IT Consulting', 'it-consulting', 'Professional & Business Services'),
('HR Consulting', 'hr-consulting', 'Professional & Business Services'),
('Staffing & Recruitment', 'staffing-recruitment', 'Professional & Business Services'),
('Outsourcing', 'outsourcing', 'Professional & Business Services'),
('Business Process Services', 'business-process-services', 'Professional & Business Services'),
('Market Intelligence', 'market-intelligence', 'Professional & Business Services'),
('Corporate Services', 'corporate-services', 'Professional & Business Services'),
('Employer Branding', 'employer-branding', 'Professional & Business Services'),

-- Niche Industries
('Climate Tech', 'climate-tech', 'Niche Industries'),
('Space Technology', 'space-technology', 'Niche Industries'),
('Defense & Security', 'defense-security', 'Niche Industries'),
('Smart Cities', 'smart-cities', 'Niche Industries'),
('Internet of Things (IoT)', 'internet-of-things-iot', 'Niche Industries'),
('Robotics', 'robotics', 'Niche Industries'),
('Nanotechnology', 'nanotechnology', 'Niche Industries'),
('Quantum Computing', 'quantum-computing', 'Niche Industries'),
('Accessibility Services', 'accessibility-services', 'Niche Industries'),
('Ethical AI', 'ethical-ai', 'Niche Industries')
ON CONFLICT (slug) DO NOTHING;
