-- Create job_categories table
CREATE TABLE IF NOT EXISTS job_categories (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL UNIQUE,
  slug TEXT NOT NULL UNIQUE,
  parent_id UUID REFERENCES job_categories(id) ON DELETE SET NULL,
  created_at TIMESTAMP DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_job_categories_slug ON job_categories(slug);
CREATE INDEX IF NOT EXISTS idx_job_categories_parent_id ON job_categories(parent_id);

-- Seed job categories
INSERT INTO job_categories (name, slug) VALUES
-- Technology & IT - Software Development
('Frontend Developer', 'frontend-developer'),
('Backend Developer', 'backend-developer'),
('Full Stack Developer', 'full-stack-developer'),
('Mobile App Development', 'mobile-app-development'),
('Game Development', 'game-development'),
('Web Development', 'web-development'),
('DevOps Engineer', 'devops-engineer'),
('Cloud Engineer', 'cloud-engineer'),
('Site Reliability Engineer (SRE)', 'site-reliability-engineer-sre'),
('Data Science', 'data-science'),
('Data Engineering', 'data-engineering'),
('Machine Learning Engineer', 'machine-learning-engineer'),
('Artificial Intelligence Engineer', 'artificial-intelligence-engineer'),
('Cybersecurity', 'cybersecurity'),
('Information Security Analyst', 'information-security-analyst'),
('Penetration Tester', 'penetration-tester'),
('Network Engineer', 'network-engineer'),
('Systems Administrator', 'systems-administrator'),
('IT Support', 'it-support'),
('Help Desk Technician', 'help-desk-technician'),
('Database Administrator', 'database-administrator'),
('Blockchain Developer', 'blockchain-developer'),
('Embedded Systems Engineer', 'embedded-systems-engineer'),
('QA Engineer', 'qa-engineer'),
('Test Automation Engineer', 'test-automation-engineer'),
('AR/VR Developer', 'ar-vr-developer'),
('Hardware Engineer', 'hardware-engineer'),
('IT Project Management', 'it-project-management'),
('Technical Product Manager', 'technical-product-manager'),

-- Design & Creative
('Graphic Design', 'graphic-design'),
('UI Design', 'ui-design'),
('UX Design', 'ux-design'),
('Product Design', 'product-design'),
('Web Design', 'web-design'),
('Motion Graphics', 'motion-graphics'),
('Animation', 'animation'),
('3D Artist', '3d-artist'),
('Game Artist', 'game-artist'),
('Illustration', 'illustration'),
('Branding', 'branding'),
('Visual Design', 'visual-design'),
('Industrial Design', 'industrial-design'),
('Interior Design', 'interior-design'),
('Fashion Design', 'fashion-design'),
('Textile Design', 'textile-design'),
('Photography', 'photography'),
('Videography', 'videography'),
('Video Editing', 'video-editing'),
('Sound Design', 'sound-design'),

-- Business, Management & Operations
('Business Administration', 'business-administration'),
('Operations Management', 'operations-management'),
('Project Management', 'project-management'),
('Program Management', 'program-management'),
('Product Management', 'product-management'),
('Business Analysis', 'business-analysis'),
('Strategy Consulting', 'strategy-consulting'),
('Management Consulting', 'management-consulting'),
('Process Improvement', 'process-improvement'),
('Quality Management', 'quality-management'),
('Risk Management', 'risk-management'),
('Compliance', 'compliance'),
('Change Management', 'change-management'),
('Office Management', 'office-management'),
('Executive Assistant', 'executive-assistant'),
('Chief Executive Officer (CEO)', 'chief-executive-officer-ceo'),
('Chief Technology Officer (CTO)', 'chief-technology-officer-cto'),
('Chief Operating Officer (COO)', 'chief-operating-officer-coo'),
('Entrepreneur / Founder', 'entrepreneur-founder'),
('Startup Operations', 'startup-operations'),

-- Finance & Accounting
('Accounting', 'accounting'),
('Bookkeeping', 'bookkeeping'),
('Financial Analysis', 'financial-analysis'),
('Corporate Finance', 'corporate-finance'),
('Investment Banking', 'investment-banking'),
('Private Equity', 'private-equity'),
('Venture Capital', 'venture-capital'),
('Asset Management', 'asset-management'),
('Wealth Management', 'wealth-management'),
('Risk Analysis', 'risk-analysis'),
('Auditing', 'auditing'),
('Tax Consulting', 'tax-consulting'),
('Payroll', 'payroll'),
('Financial Controller', 'financial-controller'),
('Treasury', 'treasury'),
('Insurance', 'insurance'),
('Actuarial Science', 'actuarial-science'),
('Credit Analysis', 'credit-analysis'),
('Compliance Finance', 'compliance-finance'),
('FinTech', 'fintech'),

-- Sales, Marketing & Growth
('Sales', 'sales'),
('Inside Sales', 'inside-sales'),
('Outside Sales', 'outside-sales'),
('Business Development', 'business-development'),
('Account Management', 'account-management'),
('Customer Success', 'customer-success'),
('Digital Marketing', 'digital-marketing'),
('Performance Marketing', 'performance-marketing'),
('Growth Marketing', 'growth-marketing'),
('Content Marketing', 'content-marketing'),
('SEO', 'seo'),
('SEM / PPC', 'sem-ppc'),
('Social Media Marketing', 'social-media-marketing'),
('Influencer Marketing', 'influencer-marketing'),
('Brand Management', 'brand-management'),
('Product Marketing', 'product-marketing'),
('Market Research', 'market-research'),
('CRM Management', 'crm-management'),
('Email Marketing', 'email-marketing'),
('Affiliate Marketing', 'affiliate-marketing'),

-- Human Resources & People
('Human Resources', 'human-resources'),
('Talent Acquisition', 'talent-acquisition'),
('Recruitment', 'recruitment'),
('Technical Recruitment', 'technical-recruitment'),
('HR Business Partner', 'hr-business-partner'),
('People Operations', 'people-operations'),
('Learning & Development', 'learning-development'),
('Training Coordinator', 'training-coordinator'),
('Organizational Development', 'organizational-development'),
('Compensation & Benefits', 'compensation-benefits'),
('Payroll HR', 'payroll-hr'),
('Employee Relations', 'employee-relations'),
('Diversity & Inclusion', 'diversity-inclusion'),
('Workforce Planning', 'workforce-planning'),
('Employer Branding', 'employer-branding'),

-- Healthcare & Life Sciences
('Healthcare Administration', 'healthcare-administration'),
('Medical Doctor', 'medical-doctor'),
('General Practitioner', 'general-practitioner'),
('Specialist Physician', 'specialist-physician'),
('Nursing', 'nursing'),
('Registered Nurse', 'registered-nurse'),
('Practical Nurse', 'practical-nurse'),
('Pharmacy', 'pharmacy'),
('Pharmacist', 'pharmacist'),
('Laboratory Technician', 'laboratory-technician'),
('Medical Research', 'medical-research'),
('Clinical Research', 'clinical-research'),
('Public Health', 'public-health'),
('Mental Health', 'mental-health'),
('Psychology', 'psychology'),
('Psychiatry', 'psychiatry'),
('Physiotherapy', 'physiotherapy'),
('Occupational Therapy', 'occupational-therapy'),
('Radiology', 'radiology'),
('Medical Imaging', 'medical-imaging'),

-- Engineering & Construction
('Civil Engineering', 'civil-engineering'),
('Structural Engineering', 'structural-engineering'),
('Mechanical Engineering', 'mechanical-engineering'),
('Electrical Engineering', 'electrical-engineering'),
('Electronics Engineering', 'electronics-engineering'),
('Industrial Engineering', 'industrial-engineering'),
('Manufacturing Engineering', 'manufacturing-engineering'),
('Process Engineering', 'process-engineering'),
('Chemical Engineering', 'chemical-engineering'),
('Petroleum Engineering', 'petroleum-engineering'),
('Mining Engineering', 'mining-engineering'),
('Construction Management', 'construction-management'),
('Site Engineer', 'site-engineer'),
('Project Engineer', 'project-engineer'),
('Quantity Surveyor', 'quantity-surveyor'),
('Architecture', 'architecture'),
('Landscape Architecture', 'landscape-architecture'),
('Urban Planning', 'urban-planning'),
('Surveying', 'surveying'),
('Building Inspection', 'building-inspection'),

-- Logistics, Transport & Supply Chain
('Supply Chain Management', 'supply-chain-management'),
('Logistics', 'logistics'),
('Transportation', 'transportation'),
('Warehouse Management', 'warehouse-management'),
('Inventory Management', 'inventory-management'),
('Procurement', 'procurement'),
('Purchasing', 'purchasing'),
('Sourcing', 'sourcing'),
('Fleet Management', 'fleet-management'),
('Distribution', 'distribution'),
('Shipping & Maritime', 'shipping-maritime'),
('Aviation Operations', 'aviation-operations'),
('Customs & Trade Compliance', 'customs-trade-compliance'),

-- Education & Research
('Education', 'education'),
('Teaching', 'teaching'),
('Primary School Teacher', 'primary-school-teacher'),
('Secondary School Teacher', 'secondary-school-teacher'),
('University Lecturer', 'university-lecturer'),
('Professor', 'professor'),
('Academic Research', 'academic-research'),
('Educational Administration', 'educational-administration'),
('Curriculum Development', 'curriculum-development'),
('Instructional Design', 'instructional-design'),
('Online Teaching', 'online-teaching'),

-- Legal & Public Sector
('Law', 'law'),
('Legal Counsel', 'legal-counsel'),
('Corporate Lawyer', 'corporate-lawyer'),
('Criminal Law', 'criminal-law'),
('Civil Law', 'civil-law'),
('Compliance & Regulation', 'compliance-regulation'),
('Public Administration', 'public-administration'),
('Government Services', 'government-services'),
('Policy Analysis', 'policy-analysis'),
('International Relations', 'international-relations'),
('Diplomacy', 'diplomacy'),

-- Optional Extras
('NGO / Non-Profit', 'ngo-non-profit'),
('Sustainability', 'sustainability'),
('Environmental Science', 'environmental-science'),
('Climate & Energy', 'climate-energy'),
('Renewable Energy', 'renewable-energy'),
('Social Work', 'social-work'),
('Community Development', 'community-development')
ON CONFLICT (slug) DO NOTHING;
